# Generated by Django 5.2.7 on 2025-11-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social')),
                ('cnpj', models.CharField(help_text='Cadastro Nacional da Pessoa Jurídica', max_length=20, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail de Contato')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone(ex: +55 21 99999-8888)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ('nome_fantasia',),
            },
        ),
    ]
