# Generated by Django 5.2.8 on 2025-11-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=20, unique=True, verbose_name='CNPJ'),
        ),
    ]
