# Generated by Django 5.2.8 on 2025-11-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_fornecedor_cnpj'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fornecedor',
            table='fornecedores',
        ),
    ]
