# Generated by Django 5.2.7 on 2025-11-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Telefone'),
        ),
    ]
