# Generated by Django 5.2.7 on 2025-11-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='statis',
            new_name='status',
        ),
    ]
