# Generated by Django 5.2.7 on 2025-11-14 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_cliente_telefone'),
        ('sales', '0002_rename_statis_venda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='customers.cliente'),
        ),
    ]
