# Generated by Django 5.2.7 on 2025-11-14 23:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_venda_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Abertura')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Inicial (Suprimento)')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('valor_final_informado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Final (Informado pelo Operador)')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_caixa', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Sessão de Caixa',
                'verbose_name_plural': 'Sessões de Caixa',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.AddField(
            model_name='venda',
            name='sessao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_na_sessao', to='sales.sessaocaixa'),
        ),
    ]
