# Generated by Django 5.2.8 on 2025-11-15 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_cliente_telefone'),
        ('sales', '0004_sessaocaixa_venda_sessao'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('DEBITO', 'Cartão de Débito'), ('CREDITO', 'Cartão de Crédito'), ('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('OUTROS', 'Outros')], default='DINHEIRO', max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='customers.cliente'),
        ),
    ]
