# Generated by Django 5.2 on 2025-11-15
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_venda_forma_pagamento_alter_venda_cliente'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SUPRIMENTO', 'Suprimento'), ('SANGRIA', 'Sangria')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_caixa', to='sales.sessaocaixa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_caixa', to='auth.user')),
            ],
            options={
                'verbose_name': 'Movimento de Caixa',
                'verbose_name_plural': 'Movimentos de Caixa',
                'ordering': ['-data_hora'],
            },
        ),
    ]
