# Generated by Django 5.2 on 2025-11-15
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_movimentocaixa'),
        ('products', '0004_produto_preco_custo_alter_produto_preco'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sessao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='sales.sessaocaixa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='auth.user')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='sales.venda')),
            ],
            options={
                'verbose_name': 'Devolução',
                'verbose_name_plural': 'Devoluções',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ItemDevolucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='sales.devolucao')),
                ('item_venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.itemvenda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.produto')),
            ],
        ),
    ]
