# Generated by Django 5.2.8 on 2025-11-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_devolucao_itemdevolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemdevolucao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movimentocaixa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='devolucao',
            table='devolucoes',
        ),
        migrations.AlterModelTable(
            name='itemdevolucao',
            table='itens_devolucao',
        ),
        migrations.AlterModelTable(
            name='itemvenda',
            table='itens_venda',
        ),
        migrations.AlterModelTable(
            name='movimentocaixa',
            table='movimentos_caixa',
        ),
        migrations.AlterModelTable(
            name='sessaocaixa',
            table='sessoes_caixa',
        ),
        migrations.AlterModelTable(
            name='venda',
            table='vendas',
        ),
    ]
