# Generated by Django 5.2.7 on 2025-11-11 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_produto_categoria_delete_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(help_text='Quantidade a ser movimentada. Use negativos para saídas/perdas.')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Manual/Compra)'), ('SAIDA_VENDA', 'Saída (Venda PDV)'), ('AJUSTE_PERDA', 'Ajuste (Perda/Dano)'), ('AJUSTE_CONTAGEM', 'Ajuste (Contagem de Estoque)')], default='ENTRADA', max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Movimento')),
                ('motivo', models.CharField(blank=True, help_text='Motivo do ajuste ou nº da nota fiscal de entrada.', max_length=255, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='products.produto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_hora'],
            },
        ),
    ]
