# Generated by Django 5.2.8 on 2025-11-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_produto_preco_custo_alter_produto_preco'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movimentoestoque',
            table='movimentos_estoque',
        ),
        migrations.AlterModelTable(
            name='produto',
            table='produtos',
        ),
    ]
