# Generated by Django 5.2.8 on 2025-11-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_movimentoestoque_table_alter_produto_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras do produto (EAN-13, EAN-8, etc.)', max_length=50, null=True, unique=True),
        ),
    ]
