# Generated by Django 5.2.8 on 2025-11-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_produto_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se o produto está ativo/visível no sistema'),
        ),
    ]
